### ISSUE TITLE
Add new voice

### ISSUE THREAD

**Issue by marlon-br** [vlomme/MelGan-WavGan#1]
Hi, in case I want to train MelGan and WavGan on a new voice, what amount of input data do i need? 1H, 10Hrs or more for a new speaker?

**Comment by vlomme** [comment]
hello. This vocoder can work with voices that you haven't seen before. But if you want, you can finish training in 1 hour. In any case, the quality will be slightly worse than WaveRNN

**Comment by marlon-br** [comment]
how many hours of the new speaker audio is required?

**Comment by vlomme** [comment]
1 hour

**Comment by marlon-br** [comment]
thanks
