### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by hellc** [vlomme/MelGan-WavGan#4]
Попробовал собрать под Windows 10. Train ни в какую не заводится. Похоже проблема с PyTorch и ее DataLoader
Перечисление тут не работает:
https://github.com/vlomme/MelGan-WavGan/blob/24f02c11c61aea7a5daf9b97776f733066033b69/wavgan.py#L120
Код отрабатывает без ошибок.
Есть советы как побороть?

**Comment by vlomme** [comment]
А вы всё сделали из инструкции? Поместили датасет куда нужно, запустили препроцессинг? mel_list содержит файлы? https://github.com/vlomme/MelGan-WavGan#%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5

**Comment by hellc** [comment]
Разумеется. Да, mel_list содержит список glim-ов. В отладке проверил.
![Untitled](https://user-images.githubusercontent.com/750178/93627209-40ec1300-f9ed-11ea-9bcb-b94ef2cd6c1d.png)
 Самый нижний брейкпоинт не срабатывает

**Comment by vlomme** [comment]
Я думаю это из-за того, что у вас файлов меньше чем batch_size. Вы же не собираетесь обучаться на 15 файлах?

**Comment by hellc** [comment]
Нет, не собираюсь. Спасибо за совет, помогло.
